openai_api_key: ${openai-api-key}
connections:
  - name: dbt_movies
    databaseName: ${db-catalog-DBT Connection}
    schemaName: ${db-schema-DBT Connection}
    dbType: databricks
    url: >-
      jdbc:databricks://${db-host-DBT
      Connection}:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=${db-httppath-DBT
      Connection};PWD=${db-token-DBT Connection}
